### ISSUE TITLE
How to read in a string?

### ISSUE THREAD

**Issue by mefellows** [bengl/sbffi#12]
Given the following c program which can be compiled into `libhello.so`:

```c
// hello.c

#include <stdio.h>

const char* hello(char* name) {
    printf("Hello %s\n", name);
    return "Hello from C\n";
}

```

and the following JS file:

```js
// index.js

const { getNativeFunction } = require('sbffi');
const sbffi = require('sbffi');

const libPath = './libhello.so';
const hello = getNativeFunction(libPath, 'hello', 'char*', ['char*']);

const buffer = Buffer.alloc(4, 'Matt');
const bufferPointer = sbffi.getBufferPointer(buffer);
const res = hello(bufferPointer);
console.log(res);
console.log(typeof helloRes);
```

I get the following output:

```
➜  sbffi git:(master) ✗ node index.js
Hello Matt
4342980508n
bigint
```

I'm assuming this is perhaps a pointer to the address of the result, but I'm unsure of what to do with it practically.

How do I read in `res` into a JS string?

**Comment by bengl** [comment]
Your best bet here is to create a second buffer to write your string into, rather than returning it. You'd pass a second buffer into the function for the result. You can use the return value of the function for the length written into the second buffer, and then do a `.toString()` on the buffer up to that point.

**Comment by mefellows** [comment]
Ah, makes sense. The library I need to link to returns a string directly, but worst case could wrap the function in another c if needed. Thank you for the answer.
